# src/ccx_agents/scaffold.py
"""Project scaffolding for ccx-agents projects.

Used by ``ccx-agents init <dir>`` to create a ready-to-run project layout.
"""

from __future__ import annotations

import os

_DEFAULT_PROJECT_TEMPLATE = """\
# {name}
#
# ccx-agents project — Route openai-agents-python through CCX.
# Generated by ``ccx-agents init``.
# https://github.com/BenedictKing/ccx

## Setup

```bash
pip install -e .
```

## Run

```bash
python main.py
```
"""

_MAIN_PY_TEMPLATE = '''\
"""{name} — ccx-agents example project."""

from ccx_agents import ccx_setup
from agents import Agent, Runner


def main() -> None:
    # 1. Point to your CCX gateway
    ccx_setup(base_url="http://localhost:3000/v1")

    # 2. Create an agent
    agent = Agent(
        name="assistant",
        instructions="You are a helpful assistant. Reply in the user\'s language.",
    )

    # 3. Run it
    result = Runner.run_sync(agent, "Hello! What can you do?")
    print(result.final_output)


if __name__ == "__main__":
    main()
'''

_PYPROJECT_TEMPLATE = '''\
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{name}"
version = "0.1.0"
description = "ccx-agents project — multi-model AI agents"
requires-python = ">=3.10"
dependencies = [
    "ccx-agents>=0.1",
    "openai-agents>=0.0.12",
]

[project.optional-dependencies]
dev = [
    "pytest>=8",
    "ruff>=0.5",
]

[tool.ruff]
line-length = 100
'''

_GITIGNORE_TEMPLATE = """\
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
venv/
.pytest_cache/
.coverage
htmlcov/
"""


def scaffold_project(dest: str, name: str) -> None:
    """Create a new ccx-agents project at *dest*.

    Creates:
        - ``README.md``
        - ``main.py``
        - ``pyproject.toml``
        - ``.gitignore``
    """
    os.makedirs(dest, exist_ok=True)

    files = {
        "README.md": _DEFAULT_PROJECT_TEMPLATE.format(name=name),
        "main.py": _MAIN_PY_TEMPLATE.format(name=name),
        "pyproject.toml": _PYPROJECT_TEMPLATE.format(name=name),
        ".gitignore": _GITIGNORE_TEMPLATE,
    }

    for filename, content in files.items():
        path = os.path.join(dest, filename)
        if os.path.exists(path):
            print(f"  ⚠️  {filename} exists — skipped")
            continue
        with open(path, "w") as f:
            f.write(content.lstrip("\n"))
        print(f"  ✅ Created {filename}")
