package channelpreset

// Code generated by scripts/generate-channel-presets.mjs; DO NOT EDIT.

func generatedCodexResponsesTargetConfigs() map[string]channelTargetConfig {
	return map[string]channelTargetConfig{
		"deepseek":       channelTargetConfig{ReasoningParamStyle: "reasoning", CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"mimo":           channelTargetConfig{ServiceType: "responses", ReasoningParamStyle: "reasoning", CodexToolCompat: boolRef(true), StripCodexClientTools: boolRef(true), RateLimitRPM: 80},
		"compshare":      channelTargetConfig{ReasoningParamStyle: "reasoning", CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"runapi":         channelTargetConfig{CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"unity2":         channelTargetConfig{CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"minimax":        channelTargetConfig{CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"dashscope":      channelTargetConfig{},
		"opencode-zen":   channelTargetConfig{ReasoningParamStyle: "reasoning"},
		"opencode-go":    channelTargetConfig{ReasoningParamStyle: "reasoning"},
		"kimi":           channelTargetConfig{},
		"glm":            channelTargetConfig{},
		"sensenova":      channelTargetConfig{},
		"openrouter":     channelTargetConfig{CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"modelscope":     channelTargetConfig{CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"volc-ark":       channelTargetConfig{ReasoningParamStyle: "reasoning", CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"qianfan":        channelTargetConfig{},
		"xfyun":          channelTargetConfig{ServiceType: "responses"},
		"github-copilot": channelTargetConfig{ServiceType: "copilot", CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"atomgit":        channelTargetConfig{ServiceType: "openai", ReasoningParamStyle: "thinking", CodexToolCompat: boolRef(true), StripCodexClientTools: boolRef(true)},
	}
}
