package channelpreset

// Code generated by scripts/generate-channel-presets.mjs; DO NOT EDIT.

func generatedClaudeMessagesTargetConfigs() map[string]channelTargetConfig {
	return map[string]channelTargetConfig{
		"deepseek":      channelTargetConfig{ReasoningParamStyle: "reasoning", NormalizeSystemRoleToTopLevel: true, NormalizeMetadataUserId: boolRef(true), StripBillingHeader: true},
		"mimo":          channelTargetConfig{ReasoningParamStyle: "thinking", NormalizeSystemRoleToTopLevel: true, RateLimitRPM: 80},
		"compshare":     channelTargetConfig{ReasoningParamStyle: "reasoning", NormalizeSystemRoleToTopLevel: true},
		"runapi":        channelTargetConfig{},
		"unity2":        channelTargetConfig{},
		"kimi":          channelTargetConfig{NormalizeSystemRoleToTopLevel: true},
		"glm":           channelTargetConfig{NormalizeSystemRoleToTopLevel: true},
		"sensenova":     channelTargetConfig{NormalizeSystemRoleToTopLevel: true},
		"minimax":       channelTargetConfig{NormalizeSystemRoleToTopLevel: true},
		"dashscope":     channelTargetConfig{NormalizeSystemRoleToTopLevel: true},
		"opencode-zen":  channelTargetConfig{ServiceType: "openai", ReasoningParamStyle: "reasoning", AuthHeader: "bearer", NormalizeSystemRoleToTopLevel: true},
		"opencode-go":   channelTargetConfig{ServiceType: "openai", ReasoningParamStyle: "reasoning", AuthHeader: "bearer", NormalizeSystemRoleToTopLevel: true},
		"modelscope":    channelTargetConfig{NormalizeSystemRoleToTopLevel: true},
		"volc-ark":      channelTargetConfig{ReasoningParamStyle: "reasoning", NormalizeSystemRoleToTopLevel: true},
		"qianfan":       channelTargetConfig{NormalizeSystemRoleToTopLevel: true},
		"xfyun":         channelTargetConfig{NormalizeSystemRoleToTopLevel: true},
		"tencent-lkeap": channelTargetConfig{NormalizeSystemRoleToTopLevel: true},
		"atomgit":       channelTargetConfig{ServiceType: "openai", ReasoningParamStyle: "thinking", NormalizeSystemRoleToTopLevel: true},
	}
}
