package channelpreset

// Code generated by scripts/generate-channel-presets.mjs; DO NOT EDIT.

func generatedOpenAIChatTargetConfigs() map[string]channelTargetConfig {
	return map[string]channelTargetConfig{
		"deepseek":     channelTargetConfig{ReasoningParamStyle: "reasoning"},
		"mimo":         channelTargetConfig{ReasoningParamStyle: "thinking", RateLimitRPM: 80},
		"compshare":    channelTargetConfig{ReasoningParamStyle: "reasoning"},
		"runapi":       channelTargetConfig{},
		"unity2":       channelTargetConfig{},
		"openrouter":   channelTargetConfig{},
		"sensenova":    channelTargetConfig{},
		"modelscope":   channelTargetConfig{},
		"minimax":      channelTargetConfig{},
		"dashscope":    channelTargetConfig{},
		"opencode-zen": channelTargetConfig{ReasoningParamStyle: "reasoning", AuthHeader: "bearer"},
		"opencode-go":  channelTargetConfig{ReasoningParamStyle: "reasoning", AuthHeader: "bearer"},
		"volc-ark":     channelTargetConfig{},
		"qianfan":      channelTargetConfig{},
		"xfyun":        channelTargetConfig{},
		"atomgit":      channelTargetConfig{ReasoningParamStyle: "thinking"},
	}
}
